baseURL = "https://fibertilalle.no/"
languageCode = "nb-NO"
title = "Fiber til alle på Skinstø"
publishdir = "docs"
theme = "beautifulhugo"
DefaultContentLanguage = "nb"

[Author]
  name = "Styret"
  website = "/page/foreningen/#styret"
  email = "post@fibertilalle.no"
  facebook = "groups/119825412031136/"

[Params]
  homeTitle = "Fiber til alle" # Set a different text for the header on the home page
  subtitle = "Et kollektivt spleiselag for beboerne på Skinstø"
  logo = "img/logo.svg"
  mainSections = ["post"]
  hideAuthor = true
  #favicon = "img/favicon.ico"

[markup.goldmark.renderer]
unsafe = true

[[menu.main]]
    name = "Om"
    url = "page/foreningen/"
    weight = 40

[[menu.main]]
    name = "Homenet"
    url = "page/homenet/"
    weight = 20

[[menu.main]]
    name = "Wifi"
    url = "page/wifi/"
    weight = 30
