baseURL = "http://fibertilalle.no/"
languageCode = "nb-NO"
title = "Fiber til alle på Skinstø"
publishdir = "docs"
theme = "beautifulhugo"
DefaultContentLanguage = "nb"

[Author]
  name = "Styret"
  website = "/page/foreningen/#styret"
  email = "post@fibertilalle.no"
  facebook = "groups/119825412031136/"

[Params]
  homeTitle = "Fiber til alle" # Set a different text for the header on the home page
  subtitle = "Et kollektivt spleiselag for beboerne på Skinstø"
  logo = "img/fiber.png"
  #favicon = "img/favicon.ico"

[[menu.main]]
    name = "Om"
    url = "page/foreningen/"
    weight = 3

[[menu.main]]
    name = "Wifi"
    url = "page/wifi/"
    weight = 3
